// Gamification and Achievements

export const ACHIEVEMENTS = [
  // Streak achievements
  {
    id: 'first_practice',
    name: 'First Step',
    nameRu: 'Первый шаг',
    description: 'Завершите первую практику',
    icon: '🌱',
    category: 'practice' as const,
    target: 1,
    rarity: 'common' as const,
  },
  {
    id: 'streak_7',
    name: 'Weekly Warrior',
    nameRu: 'Неделя силы',
    description: '7 дней практики подряд',
    icon: '🔥',
    category: 'streak' as const,
    target: 7,
    rarity: 'common' as const,
  },
  {
    id: 'streak_30',
    name: 'Monthly Master',
    nameRu: 'Месяц трансформации',
    description: '30 дней практики подряд',
    icon: '⭐',
    category: 'streak' as const,
    target: 30,
    rarity: 'rare' as const,
  },
  {
    id: 'streak_100',
    name: 'Century Champion',
    nameRu: 'Мастер дисциплины',
    description: '100 дней практики подряд',
    icon: '👑',
    category: 'streak' as const,
    target: 100,
    rarity: 'legendary' as const,
  },
  // Practice achievements
  {
    id: 'practices_10',
    name: 'Getting Started',
    nameRu: 'Начинающий йог',
    description: '10 завершённых практик',
    icon: '🧘',
    category: 'practice' as const,
    target: 10,
    rarity: 'common' as const,
  },
  {
    id: 'practices_50',
    name: 'Dedicated Practitioner',
    nameRu: 'Опытный практик',
    description: '50 завершённых практик',
    icon: '💪',
    category: 'practice' as const,
    target: 50,
    rarity: 'rare' as const,
  },
  {
    id: 'practices_100',
    name: 'Yoga Enthusiast',
    nameRu: 'Йога-энтузиаст',
    description: '100 завершённых практик',
    icon: '🎯',
    category: 'practice' as const,
    target: 100,
    rarity: 'epic' as const,
  },
  // AI achievements
  {
    id: 'vision_first',
    name: 'AI Analysis',
    nameRu: 'AI-анализ',
    description: 'Первый анализ асаны с AI',
    icon: '📸',
    category: 'ai' as const,
    target: 1,
    rarity: 'common' as const,
  },
  {
    id: 'meditation_first',
    name: 'Inner Peace',
    nameRu: 'Внутренний покой',
    description: 'Первая AI-медитация',
    icon: '🕊️',
    category: 'ai' as const,
    target: 1,
    rarity: 'common' as const,
  },
  {
    id: 'all_modes',
    name: 'AI Explorer',
    nameRu: 'Исследователь AI',
    description: 'Попробовать все режимы Aria',
    icon: '🔮',
    category: 'ai' as const,
    target: 6,
    rarity: 'rare' as const,
  },
  // Inside Flow achievements
  {
    id: 'inside_flow_first',
    name: 'Flow Beginner',
    nameRu: 'Поток начинается',
    description: 'Первый Inside Flow класс',
    icon: '🎵',
    category: 'practice' as const,
    target: 1,
    rarity: 'common' as const,
  },
  {
    id: 'inside_flow_10',
    name: 'Flow Master',
    nameRu: 'Мастер потока',
    description: '10 Inside Flow классов',
    icon: '🎶',
    category: 'practice' as const,
    target: 10,
    rarity: 'rare' as const,
  },
  // New achievements 2026
  {
    id: 'music_sync',
    name: 'Music Flow',
    nameRu: 'В ритме музыки',
    description: '5 практик Inside Flow с музыкой',
    icon: '🎧',
    category: 'practice' as const,
    target: 5,
    rarity: 'common' as const,
  },
  {
    id: 'ai_daily_7',
    name: 'AI Assistant',
    nameRu: 'AI-ассистент',
    description: 'Общение с Aria 7 дней подряд',
    icon: '🤖',
    category: 'ai' as const,
    target: 7,
    rarity: 'common' as const,
  },
  {
    id: 'vision_progress',
    name: 'Visible Progress',
    nameRu: 'Видимый прогресс',
    description: '10 анализов асан с улучшением',
    icon: '📈',
    category: 'ai' as const,
    target: 10,
    rarity: 'rare' as const,
  },
  {
    id: 'breathwork_master',
    name: 'Breathwork Master',
    nameRu: 'Мастер дыхания',
    description: '20 дыхательных практик',
    icon: '💨',
    category: 'practice' as const,
    target: 20,
    rarity: 'rare' as const,
  },
  {
    id: 'morning_bird',
    name: 'Early Bird',
    nameRu: 'Ранняя пташка',
    description: '10 утренних практик (до 9:00)',
    icon: '🌅',
    category: 'milestone' as const,
    target: 10,
    rarity: 'common' as const,
  },
  {
    id: 'evening_calm',
    name: 'Evening Calm',
    nameRu: 'Вечерний покой',
    description: '10 вечерних практик (после 19:00)',
    icon: '🌙',
    category: 'milestone' as const,
    target: 10,
    rarity: 'common' as const,
  },
  {
    id: 'weekly_goal',
    name: 'Goal Achiever',
    nameRu: 'Цель достигнута',
    description: 'Выполнить недельную цель 4 раза',
    icon: '🎯',
    category: 'milestone' as const,
    target: 4,
    rarity: 'rare' as const,
  },
  {
    id: 'personal_program',
    name: 'Program Complete',
    nameRu: 'Программа завершена',
    description: 'Завершить 7-дневную AI-программу',
    icon: '📋',
    category: 'ai' as const,
    target: 1,
    rarity: 'rare' as const,
  },
] as const;

export const STREAK_MILESTONES = [
  { days: 3, reward: 'Bronze Badge', rewardRu: 'Бронзовый значок', icon: '🥉' },
  { days: 7, reward: 'Silver Badge', rewardRu: 'Серебряный значок', icon: '🥈' },
  { days: 14, reward: 'Gold Badge', rewardRu: 'Золотой значок', icon: '🥇' },
  { days: 30, reward: 'Diamond Badge', rewardRu: 'Бриллиантовый значок', icon: '💎' },
  { days: 60, reward: 'Platinum Badge', rewardRu: 'Платиновый значок', icon: '🏆' },
  { days: 100, reward: 'Legend Badge', rewardRu: 'Легендарный значок', icon: '👑' },
] as const;
