// Pricing and Subscription Plans
export const PRICING_PLANS = [
  {
    id: 'single',
    title: 'Разовое занятие',
    price: 700,
    currency: 'RUB',
    description: 'Для знакомства со студией',
    features: ['1 посещение любой практики', 'Коврик включен', 'Чай после практики'],
    validDays: 7,
    isPopular: false,
  },
  {
    id: 'pack-4',
    title: 'Абонемент 4 занятия',
    price: 2500,
    currency: 'RUB',
    description: 'Срок 1 месяц с первого посещения',
    features: ['625 ₽ за занятие', '4 посещения', 'Экономия 300 ₽'],
    validDays: 30,
    isPopular: false,
  },
  {
    id: 'pack-9',
    title: 'Абонемент 9 занятий',
    price: 5000,
    currency: 'RUB',
    description: 'Срок 1 месяц с первого посещения',
    features: ['556 ₽ за занятие', '9 посещений', 'Экономия 1300 ₽'],
    validDays: 30,
    isPopular: true,
  },
  {
    id: 'unlimited',
    title: 'Безлимит 1 месяц',
    price: 8000,
    currency: 'RUB',
    description: 'Неограниченное количество посещений',
    features: ['Безлимитные посещения', 'Все направления', 'Максимальная выгода'],
    validDays: 30,
    isPopular: false,
  },
  {
    id: 'personal-1',
    title: 'Персональная тренировка',
    price: 1800,
    currency: 'RUB',
    description: '1 человек',
    features: ['Индивидуальный подход', 'Удобное время', 'Разбор техники асан'],
    validDays: 30,
    isPopular: false,
  },
  {
    id: 'personal-2',
    title: 'Персональная тренировка',
    price: 2500,
    currency: 'RUB',
    description: '2 человека',
    features: ['Занятие вдвоём', 'Удобное время', 'Индивидуальный подход'],
    validDays: 30,
    isPopular: false,
  },
] as const;

// 2026 Subscription Plans (App)
export const SUBSCRIPTION_PLANS = [
  {
    id: 'free' as const,
    name: 'Free',
    nameRu: 'Бесплатный',
    price: 0,
    currency: 'RUB' as const,
    interval: 'month' as const,
    features: [
      'AI-чат с Арией (100 сообщений/день)',
      '3 видео в неделю',
      'Дыхательные практики',
      'Базовый трекинг прогресса',
    ],
    limits: {
      aiMessagesPerDay: 100,
      videosPerWeek: 3,
      offlineDownloads: false,
      personalPrograms: false,
      visionAnalysesPerMonth: 5,
      prioritySupport: false,
    },
  },
  {
    id: 'premium' as const,
    name: 'Premium',
    nameRu: 'Премиум',
    price: 990,
    currency: 'RUB' as const,
    interval: 'month' as const,
    features: [
      'Все функции Free',
      'Безлимитные AI-сообщения',
      'Полная видеотека',
      'Скачивание для offline',
      'Персональные AI-программы',
      'Безлимитный анализ асан',
    ],
    limits: {
      aiMessagesPerDay: -1, // unlimited
      videosPerWeek: -1, // unlimited
      offlineDownloads: true,
      personalPrograms: true,
      visionAnalysesPerMonth: -1, // unlimited
      prioritySupport: false,
    },
  },
  {
    id: 'vip' as const,
    name: 'VIP',
    nameRu: 'VIP',
    price: 2990,
    currency: 'RUB' as const,
    interval: 'month' as const,
    features: [
      'Все функции Premium',
      'Личные консультации с Катей (2/мес)',
      'Приоритетная поддержка',
      'Эксклюзивный контент',
      'Ранний доступ к новым функциям',
    ],
    limits: {
      aiMessagesPerDay: -1,
      videosPerWeek: -1,
      offlineDownloads: true,
      personalPrograms: true,
      visionAnalysesPerMonth: -1,
      prioritySupport: true,
    },
  },
] as const;
