#!/bin/bash

# setup-prod-env.sh
# Helper script to configure production environment variables

echo "🧘 K Sebe Yoga Studio - Production Setup"
echo "======================================"

# Check if .env.production exists
if [ -f ".env.production" ]; then
  echo "⚠️  .env.production already exists."
  read -p "Overwrite? (y/N) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Exiting."
    exit 1
  fi
fi

echo "Please enter your Supabase configuration:"
read -p "VITE_SUPABASE_URL: " SUPABASE_URL
read -p "VITE_SUPABASE_ANON_KEY: " SUPABASE_ANON_KEY

echo ""
echo "Please enter Payment configuration:"
echo "(Leave blank if using 'Request Mode' only)"
read -p "PAYMENT_CHECKOUT_URL: " PAYMENT_URL

cat <<EOF > .env.production
# Production Environment Configuration
# Generated by setup-prod-env.sh

VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
PAYMENT_CHECKOUT_URL=$PAYMENT_URL

# Web Specific
VITE_APP_URL=https://ksebe-studio.ru

# App Specific
VITE_PWA_START_URL=/
EOF

echo ""
echo "✅ .env.production created successfully."
echo "   Don't forget to add these secrets to your Vercel/Netlify dashboard!"
